#pragma once

namespace Providers {
enum ProvidersEnum {
    CLIMATE_TEMP, //
    CLIMATE_HUMIDITY,
    OUTSIDE_TEMP,
    CLOCK,
    SOIL_MOISTURE,
    CLIMATE_FAN,
    HEATING_POWER,
    HEATER_SURFACE_TEMP,
    HEATING_SURFACE_FAN,
    HEATING_ELEMENT,
    HEATING_POWER_RELAY,
    VIOLET_SPECTRUM,
    BROAD_SPECTRUM,
    SIZE
};
}