#pragma once

// The names of the providers below are part of the prompt API
enum class DataProviders {
    CLIMATE_TEMP, //
    CLIMATE_HUMIDITY,
    CLIMATE_HUMIDITY_SETPOINT,
    AMBIENT_TEMP,
    CLOCK,
    SOIL_MOISTURE,
    SOIL_MOISTURE_SETPOINT,
    CLIMATE_FAN,
    HEATING_POWER,
    HEATING_SETPOINT,
    HEATING_SURFACE_TEMP,
    HEATING_SURFACE_FAN,
    HEATING_ELEMENT,
    VIOLET_SPECTRUM,
    BROAD_SPECTRUM,
    PUMP,
    FLUID_INJECTED,
    FLUID_INJECTED_CUMULATIVE,
    FLUID_EFFECT,
    SIZE
};
