# Changes here will be overwritten by Copier
_commit: v0.0.6
_src_path: git@github.com:krakakai/scaffolding.git
copyright_date: '2024'
copyright_holder: Stan Verschuuren
copyright_holder_email: N/A
copyright_license: GNU Lesser General Public License v2.1
global_namespace: krk
owner_email: N/A
owner_fullname: Stan Verschuuren
owner_username: s-t-a-n
project_description: C++ Arduino project for a running a little greenhouse 
project_name: KasKas
